export const RESOURCES = {
  PROJECT: "PROJECT",
  PROJECT_MEMBER: "PROJECT_MEMBER",
  TASK: "TASK",
  FILTER: "FILTER",
  FILTER_VALUE: "FILTER_VALUE",
  PAGE: "PAGE",
  CHANNEL: "CHANNEL", 
  CHANNEL_MEMBER: "CHANNEL_MEMBER",
  CHANNEL_MESSAGE: "CHANNEL_MESSAGE",
};

export const ACTOR = {
  USER: "USER",
  SYSTEM: "SYSTEM",
};
